### PR TITLE
Move symbols from sensor_util into respective files

### PR DESCRIPTION
**Pull request by Lytigas**
\<overanalsysis\>
I think everyone would agree that `sensor_util.rs` is a bad pattern, as is [SensorUtil](https://first.wpi.edu/FRC/roborio/release/docs/cpp/classfrc_1_1SensorUtil.html) in WPILib. If check methods or port counts are exposed to the user, they should be next to the hardware they relate to in the module tree.

However, there is the question of whether `check_*` or `NUM_*` should be public at all. This PR has them private, because users *could* just do, for example: `DigitalInput::new(100).is_ok()`. In most cases, constructors exit immediately if the check fails. Besides, I don't think people typically do those checks anyway.

On the other hand there's an argument for flexibility. If we don't make check methods public, we may want to guarantee that constructing invalid port id invokes very little overhead before erroring.
\</overanalysis\>

### CODE REVIEW

**Comment by Lytigas** [comment]
@auscompgeek any thoughts on this clearly very important API decision?

**Comment by jmeggitt** [comment]
@Lytigas, I think that it is completely unneeded in the first place since all the functions only contain a single if statement, It seems like it makes more sense to just remove the function entirely and do the check where it is needed. The `new` method could be more readable if the first if statement reflected what it was actually trying to check.

```cpp
HAL_Bool HAL_CheckAnalogModule(int32_t module) { 
  return module == 1;
 }

HAL_Bool HAL_CheckAnalogInputChannel(int32_t channel) {
  return channel < kNumAnalogInputs && channel >= 0;
}
```


Using `allwpilib/wpilibc/src/main/native/cpp/AnalogInput.cpp` as an example, I think that this method should be rewritten.
```cpp
AnalogInput::AnalogInput(int channel) {
  if (!SensorUtil::CheckAnalogInputChannel(channel)) {
    wpi_setWPIErrorWithContext(ChannelIndexOutOfRange,
                               "Analog Input " + wpi::Twine(channel));
    return;
  }
  // etc...
```

In my opinion I think it should look like more like this:
```cpp
AnalogInput::AnalogInput(unsigned int channel) {
  if (channel >= AnalogInput::kNumAnalogInputs) {
    wpi_setWPIErrorWithContext(ChannelIndexOutOfRange,
                               "Analog Input " + wpi::Twine(channel));
    return;
  }
  // etc...
```

**Comment by auscompgeek** [comment]
Several of these checks are already done in the HAL. Better to allow the HAL to give a correct error message than having none at all.

**Comment by Lytigas** [comment]
I would agree with that; for now I'll just merge this.

**Pull request merged**
