### PR TITLE
Make usage reporting safe

### PR DESCRIPTION
**Pull request by auscompgeek**
HAL_Report expects a null-terminated string to be passed as feature.
This ensures that a valid UTF-8 null-terminated string is passed in,
making report_usage_extras a safe wrapper around HAL_Report.

This also adds a report_usage_context function to allow for the
otherwise lost ability to pass in a null pointer as feature.

Also return the return value of HAL_Report, in case anyone actually
finds it useful.

### CODE REVIEW

**Comment by Lytigas** [comment]
Fixed the commit message

**Comment by auscompgeek** [comment]
Seems good. I wonder whether it'd be better to have users pass in a CString instead of a u8 slice. Hm.

Wait, did you actually want a Signed-off-by line?

**Comment by Lytigas** [comment]
Just wanted to check it was along what you were going for.

**Comment by auscompgeek** [comment]
Fair. I do think forcing users to null-terminate the string themselves is a bit awkward, but the alternative is to have users construct a CString. Not sure which is more ergonomic.

**Pull request merged**
