### PR TITLE
Remove extra thread from DriverStation

### PR DESCRIPTION
**Pull request by Lytigas**
Solves  #6.

I thought about it, and I think it's against my general vision for the project to opaquely spawn another thread if its not necessary. The only purpose of the extra thread in the official WPILib is to track the pressing and releasing of buttons, something users of this library should be more than capable of doing themselves if they want to. It's also confusing because you can miss a press if a button is pressed and released out of sync with the end-user's main loop.

Seeing as synchronization and waiting is all handled behind the scenes in the HAL, (which already spawns another thread to listed for DS packets) I think it makes sense to defer this decision to the user.

What I'm not quite sure about is whether the custom types for Joystick indexes are a good idea. My rationale is this: Most users will create one or two Joysticks once, so it's better to have errors there rather than more potential errors when accessing a button.

Looking for thoughts on this one.

EDIT:
Also included is a check to make sure a `RobotBase` is not constructed multiple times.

### CODE REVIEW

**Comment by jmeggitt** [comment]
I think using lazy static might be a good idea.

**Comment by Lytigas** [comment]
I'll merge this soon if no one is opposed.

**Comment by jmeggitt** [comment]
Why did you delete joystick.rs?

**Comment by jmeggitt** [comment]
After thinking about it a bit more, I think that joysticks being part of the driver station makes sense, but I still like merging the files is not the right way to go.

The driver station has three main functions: getting inputs from controls, getting details about the match, and reporting information to the user. Maybe the driver station would work better as a module of it's main components.

Also on a side note, not everything is a joystick. `get_port(port_number: usize) -> Result<DsPort, NotFound>` and 'DsPort:: button(channel: usize) -> Result<bool, JoystickUnplugged>' make a lot more sense to me. Anything besides getting unplugged should be a panic since if the button does not exist, they need to fix their code, not try to handle the possible error.

```rust
pub const BUTTON_CHANNEL: usize = 6;

let mut left_joystick = match ds.get_port(3) {
    Ok(v) => v,
   Err(e) => e.wait_for_connection(/* possible timeout? */),
};

// Default to false if unplugged.
let my_custom_button = left_joystick.button(BUTTON_CHANNEL)?; 

```

**Comment by jmeggitt** [comment]
Looks good for merge

**Pull request merged**
