### PR TITLE
Add thread backed Notifier struct

### PR DESCRIPTION
**Pull request by Redrield**

### CODE REVIEW

**Comment by Lytigas** [comment]
Thanks for contributing! If you're having linter troubles, I'd recommend ensuring that you have cargo fmt working on your machine and try running `make ci` to ensure clippy is happy.

**Comment by Lytigas** [comment]
I think the `Arc` in the notifier thread keeps the `Alarm` alive forever, meaning the thread won't exit when dropped. Let me know if I've missed something.

I would replace the notifier thread reference with `sync::Weak` and implement a `Drop` for `Notifier` that calls `mem::drop` on the main thread `Arc` and then joins the notifier thread handle.

**Comment by Redrield** [comment]
Instead I could keep a reference to the `Arc` in Notifier, and call stop() on the alarm in a Drop impl. When wait() is interrupted via stop(), it'll return 0 for the time the notifier stopped, which reaches that branch and ends the loop

**Comment by Lytigas** [comment]
I think we should save a handle to the thread and join it; that's also what the official implementation does.

**Comment by Redrield** [comment]
I tried that, JoinHandle::join is a move, which can't be done in a borrowed function call

**Comment by Lytigas** [comment]
Ah right, of course. Something like [this](https://stackoverflow.com/questions/41331577/joining-a-thread-in-a-method-that-takes-mut-self-like-drop-results-in-cann/42791007#42791007), then?

**Comment by Redrield** [comment]
Using the Option::take method wouldn't be a terrible idea, as the loop would exit once upon the next iteration after Alarm::stop, and thus join() wouldn't block indefinitely

**Comment by auscompgeek** [comment]
If the callback takes an indefinite amount of time, things could go badly. I wonder whether there's a team out there who has deadlocked their robot code using Notifier at some point.

**Comment by Redrield** [comment]
The options I see for this are
1. What @Lytigas linked, have a method that moves `self`, and panic in the Drop impl
2. Keep a reference to the join handle in an Option, `take()` that in the Drop impl and join on that handle
3. Only keep a reference to the shared notifier alarm, call `stop()` in the Drop impl, and assume the thread will eventually join on its own

The question becomes what the best option out of those is.

**Comment by auscompgeek** [comment]
I think panicking in Drop is a bad idea. Logging a warning instead might be a good idea.

I think 2 and 3 are the better options here though. Then it comes down to a matter of whether my concern would come up often enough. Hopefully teams won't shoot themselves in the foot.

**Pull request merged**
